http_server:
  url: ":8080"
  readTimeout: 600s
  writeTimeout: 600s
  shutdownTimeout: 600s

postgres:
  username: "admin"
  host: "localhost"
  port: 5432
  dbname: "postgres"
  sslmode: "disable"
  migrations_run: true
  migrations_path: "./migrations"

redis:
  user: "admin"
  host: "localhost"
  port: 6379
  db: 0

logger:
  type: "dev"
  level: "debug"
  add_source: true
  is_json: true
  set_default: true

storage:
  minio:
    address: "localhost:9000"
    user: "admin"
    bucket: "advert"
    use_ssl: false

controller:
  telegram:
    timeout: 10s
  mode: DEBUG

usecase:
 ai:
  llm: "google/gemini-2.0-flash-lite-preview-02-05:free"
  address: "https://openrouter.ai/api/v1/chat/completions"
